Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.linear_model import LogisticRegression
# YOUR CODE HERE


print(f"Logistic Regression Accuracy: {accuracy_score(y_moon, y_pred_lr):.3f}")
print(f"SVM (RBF) Accuracy: {accuracy_score(y_moon, svm_rbf.predict(X_moon_scaled)):.3f}")


------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[5][39m[32m, line 5[39m
[32m      1[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01msklearn[39;00m[34;01m.[39;00m[34;01mlinear_model[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m LogisticRegression
[32m      2[39m [38;5;66;03m# YOUR CODE HERE[39;00m
[32m----> [39m[32m5[39m [38;5;28mprint[39m([33mf[39m[33m"[39m[33mLogistic Regression Accuracy: [39m[38;5;132;01m{[39;00maccuracy_score(y_moon,[38;5;250m [39m[43my_pred_lr[49m)[38;5;132;01m:[39;00m[33m.3f[39m[38;5;132;01m}[39;00m[33m"[39m)
[32m      6[39m [38;5;28mprint[39m([33mf[39m[33m"[39m[33mSVM (RBF) Accuracy: [39m[38;5;132;01m{[39;00maccuracy_score(y_moon,[38;5;250m [39msvm_rbf.predict(X_moon_scaled))[38;5;132;01m:[39;00m[33m.3f[39m[38;5;132;01m}[39;00m[33m"[39m)

[31mNameError[39m: name 'y_pred_lr' is not defined

